import { Hai } from './types/hai';

export const HAIS: Hai[] = [
  {
    id: 1,
    number: 1,
    kind: 'manzu',
    yaochu: true,
    image: 'assets/img/manzu_all/p_ms1_1.gif',
  },
  {
    id: 2,
    number: 2,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms2_1.gif',
  },
  {
    id: 3,
    number: 3,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms3_1.gif',
  },
  {
    id: 4,
    number: 4,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms4_1.gif',
  },
  {
    id: 5,
    number: 5,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms5_1.gif',
  },
  {
    id: 6,
    number: 6,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms6_1.gif',
  },
  {
    id: 7,
    number: 7,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms7_1.gif',
  },
  {
    id: 8,
    number: 8,
    kind: 'manzu',
    yaochu: false,
    image: 'assets/img/manzu_all/p_ms8_1.gif',
  },
  {
    id: 9,
    number: 9,
    kind: 'manzu',
    yaochu: true,
    image: 'assets/img/manzu_all/p_ms9_1.gif',
  },
  {
    id: 10,
    number: 1,
    kind: 'pinzu',
    yaochu: true,
    image: 'assets/img/pinzu_all/p_ps1_1.gif',
  },
  {
    id: 11,
    number: 2,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps2_1.gif',
  },
  {
    id: 12,
    number: 3,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps3_1.gif',
  },
  {
    id: 13,
    number: 4,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps4_1.gif',
  },
  {
    id: 14,
    number: 5,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps5_1.gif',
  },
  {
    id: 15,
    number: 6,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps6_1.gif',
  },
  {
    id: 16,
    number: 7,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps7_1.gif',
  },
  {
    id: 17,
    number: 8,
    kind: 'pinzu',
    yaochu: false,
    image: 'assets/img/pinzu_all/p_ps8_1.gif',
  },
  {
    id: 18,
    number: 9,
    kind: 'pinzu',
    yaochu: true,
    image: 'assets/img/pinzu_all/p_ps9_1.gif',
  },
  {
    id: 19,
    number: 1,
    kind: 'sozu',
    yaochu: true,
    image: 'assets/img/sozu_all/p_ss1_1.gif',
  },
  {
    id: 20,
    number: 2,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss2_1.gif',
  },
  {
    id: 21,
    number: 3,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss3_1.gif',
  },
  {
    id: 22,
    number: 4,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss4_1.gif',
  },
  {
    id: 23,
    number: 5,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss5_1.gif',
  },
  {
    id: 24,
    number: 6,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss6_1.gif',
  },
  {
    id: 25,
    number: 7,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss7_1.gif',
  },
  {
    id: 26,
    number: 8,
    kind: 'sozu',
    yaochu: false,
    image: 'assets/img/sozu_all/p_ss8_1.gif',
  },
  {
    id: 27,
    number: 9,
    kind: 'sozu',
    yaochu: true,
    image: 'assets/img/sozu_all/p_ss9_1.gif',
  },
  {
    id: 28,
    character: '東',
    kind: 'fonpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_e_1.gif',
  },
  {
    id: 29,
    character: '南',
    kind: 'fonpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_s_1.gif',
  },
  {
    id: 30,
    character: '西',
    kind: 'fonpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_w_1.gif',
  },
  {
    id: 31,
    character: '北',
    kind: 'fonpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_n_1.gif',
  },
  {
    id: 32,
    character: '白',
    kind: 'sangenpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_no_1.gif',
  },
  {
    id: 33,
    character: '發',
    kind: 'sangenpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_h_1.gif',
  },
  {
    id: 34,
    character: '中',
    kind: 'sangenpai',
    yaochu: true,
    image: 'assets/img/tupai_all/p_ji_c_1.gif',
  },
];
